### ISSUE TITLE
DC compatibility

### ISSUE THREAD

**Issue by snoopotic** [NetworkedAssets/personal-repositories-for-bitbucket-server#2]
Hi. is it possible to make this Plugin Compatible with Atlassian DC or Check for possible Compatibility-Issues?

**Comment by xszuflax** [comment]
Hello,

Personal Repositories for Bitbucket Server is no longer under active development. I'm afraid that we do not plan any changes to the existing codebase and the feature set. As we believe in Open Source initiatives, we decided to pay back to the community and share our work to whoever is interested in it in the form of a public GitHub repository.

Regards,
Marcin Tomkow
