### ISSUE TITLE
LICENSE is invalid 

### ISSUE THREAD

**Issue by snoopotic** [NetworkedAssets/personal-repositories-for-bitbucket-server#4]
Hi,
I found out the LICENSE file is a dummyfile. This is no valid License and so it is formally not possible to make any changes or updates on this plugin.
Is this the maintainer's intention?
Can you update thew license or give a comment what the intention is? 
Thank you.

**Comment by xszuflax** [comment]
Hello,

Personal Repositories for Bitbucket Server is no longer under active development. I saw that you already created a merge request with a fix for a license issue. I will merge it to the main branch. Thank you very much!

Regards,
Marcin Tomkow

**Comment by snoopotic** [comment]
Hi thank you for your response.
Well, THIS issue does not belong to the plugins licencing issue.
This issue relates to the Source-code license. 
As I found people willing to develop this code further, they cannot use this code as it has no copyright information/license. 
I kindly ask you if you mind giving it MIT license or similar, them this code can be forked. And maybe given back here ;)
