### ISSUE TITLE
No longer works with BitBucket v7.3.0

### ISSUE THREAD

**Issue by sftwr-ngnr** [NetworkedAssets/personal-repositories-for-bitbucket-server#5]
Any chance this can be upgraded to make it work again with BitBucket v7.3.0?

**Comment by snoopotic** [comment]
I don't think so. :/
BitBucket API has significantly changed and this code here has no License. So no Copyright/Cooyleft is inherited. It's just Code to watch. :.(

**Comment by sftwr-ngnr** [comment]
OK, thanks :(
Can you suggest any alternative?

**Comment by snoopotic** [comment]
We managed to take some risks and do not use this plugin anymore.
So we manged it organisationally.
